# -*- coding: utf-8 -*-
"""Math201-Saras Ai week 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XInipdpeoXuI6q-aXsFu_38w-o1ZV6Pi

**Load FashionMNIST dataset using a deep learning library**
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.datasets import fashion_mnist

"""**Load the FashionMNIST Dataset**"""

# Load dataset
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

# Print shapes
print("Training data shape:", X_train.shape)
print("Training labels shape:", y_train.shape)
print("Test data shape:", X_test.shape)
print("Test labels shape:", y_test.shape)

"""**Define Class Labels**"""

class_names = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

"""**Data Preprocessing**"""

# Normalize pixel values (0–255 → 0–1)
X_train = X_train / 255.0
X_test = X_test / 255.0

# Check value range
print("Min pixel value:", X_train.min())
print("Max pixel value:", X_train.max())

"""**Visualize Sample Images**"""

plt.figure(figsize=(10, 5))

for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(X_train[i], cmap="gray")
    plt.title(class_names[y_train[i]])
    plt.axis("off")

plt.tight_layout()
plt.show()

"""**Category Distribution**"""

plt.figure(figsize=(10, 4))
sns.countplot(x=y_train)
plt.xticks(ticks=range(10), labels=class_names, rotation=45)
plt.title("Distribution of Fashion Categories in Training Set")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

"""**Images per Category**"""

plt.figure(figsize=(10, 6))

for i in range(10):
    idx = np.where(y_train == i)[0][0]
    plt.subplot(2, 5, i + 1)
    plt.imshow(X_train[idx], cmap="gray")
    plt.title(class_names[i])
    plt.axis("off")

plt.tight_layout()
plt.show()

"""**Basic Dataset Insights**"""

print("Number of training samples:", X_train.shape[0])
print("Number of test samples:", X_test.shape[0])
print("Image dimensions:", X_train.shape[1], "x", X_train.shape[2])
print("Number of classes:", len(class_names))

"""**EDA Summary**

### Exploratory Data Analysis Summary

- The FashionMNIST dataset contains 60,000 training images and 10,000 test images.
- Each image is a 28×28 grayscale representation of a fashion item.
- Pixel values were normalized to the range [0, 1] for stable neural network training.
- The dataset is well-balanced across all 10 categories.
- Visual inspection shows clear structural differences between footwear, clothing, and accessories.
- Some classes (e.g., Shirt vs T-shirt/top) appear visually similar, indicating a potential challenge for classification models.
"""